[project]
name = "fpindexcluster"
version = "0.1.0"
description = "AcoustID fingerprint index cluster service"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.8.0",
    "nats-py>=2.3.0",
    "msgspec>=0.18.0",
    "click>=8.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0.0",
    "pytest-aiohttp>=1.0.0",
    "pytest-asyncio>=0.21.0",
    "nats-py>=2.3.0",  # For real NATS connections in tests
]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"