// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: index.proto

#ifndef PROTOBUF_INCLUDED_index_2eproto
#define PROTOBUF_INCLUDED_index_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_index_2eproto 

namespace protobuf_index_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[15];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_index_2eproto
namespace Acoustid {
namespace Server {
namespace PB {
class CreateIndexRequest;
class CreateIndexRequestDefaultTypeInternal;
extern CreateIndexRequestDefaultTypeInternal _CreateIndexRequest_default_instance_;
class CreateIndexResponse;
class CreateIndexResponseDefaultTypeInternal;
extern CreateIndexResponseDefaultTypeInternal _CreateIndexResponse_default_instance_;
class DeleteDocumentRequest;
class DeleteDocumentRequestDefaultTypeInternal;
extern DeleteDocumentRequestDefaultTypeInternal _DeleteDocumentRequest_default_instance_;
class DeleteDocumentResponse;
class DeleteDocumentResponseDefaultTypeInternal;
extern DeleteDocumentResponseDefaultTypeInternal _DeleteDocumentResponse_default_instance_;
class DeleteIndexRequest;
class DeleteIndexRequestDefaultTypeInternal;
extern DeleteIndexRequestDefaultTypeInternal _DeleteIndexRequest_default_instance_;
class DeleteIndexResponse;
class DeleteIndexResponseDefaultTypeInternal;
extern DeleteIndexResponseDefaultTypeInternal _DeleteIndexResponse_default_instance_;
class GetDocumentRequest;
class GetDocumentRequestDefaultTypeInternal;
extern GetDocumentRequestDefaultTypeInternal _GetDocumentRequest_default_instance_;
class GetDocumentResponse;
class GetDocumentResponseDefaultTypeInternal;
extern GetDocumentResponseDefaultTypeInternal _GetDocumentResponse_default_instance_;
class GetIndexRequest;
class GetIndexRequestDefaultTypeInternal;
extern GetIndexRequestDefaultTypeInternal _GetIndexRequest_default_instance_;
class GetIndexResponse;
class GetIndexResponseDefaultTypeInternal;
extern GetIndexResponseDefaultTypeInternal _GetIndexResponse_default_instance_;
class InsertOrUpdateDocumentRequest;
class InsertOrUpdateDocumentRequestDefaultTypeInternal;
extern InsertOrUpdateDocumentRequestDefaultTypeInternal _InsertOrUpdateDocumentRequest_default_instance_;
class InsertOrUpdateDocumentResponse;
class InsertOrUpdateDocumentResponseDefaultTypeInternal;
extern InsertOrUpdateDocumentResponseDefaultTypeInternal _InsertOrUpdateDocumentResponse_default_instance_;
class SearchRequest;
class SearchRequestDefaultTypeInternal;
extern SearchRequestDefaultTypeInternal _SearchRequest_default_instance_;
class SearchResponse;
class SearchResponseDefaultTypeInternal;
extern SearchResponseDefaultTypeInternal _SearchResponse_default_instance_;
class SearchResult;
class SearchResultDefaultTypeInternal;
extern SearchResultDefaultTypeInternal _SearchResult_default_instance_;
}  // namespace PB
}  // namespace Server
}  // namespace Acoustid
namespace google {
namespace protobuf {
template<> ::Acoustid::Server::PB::CreateIndexRequest* Arena::CreateMaybeMessage<::Acoustid::Server::PB::CreateIndexRequest>(Arena*);
template<> ::Acoustid::Server::PB::CreateIndexResponse* Arena::CreateMaybeMessage<::Acoustid::Server::PB::CreateIndexResponse>(Arena*);
template<> ::Acoustid::Server::PB::DeleteDocumentRequest* Arena::CreateMaybeMessage<::Acoustid::Server::PB::DeleteDocumentRequest>(Arena*);
template<> ::Acoustid::Server::PB::DeleteDocumentResponse* Arena::CreateMaybeMessage<::Acoustid::Server::PB::DeleteDocumentResponse>(Arena*);
template<> ::Acoustid::Server::PB::DeleteIndexRequest* Arena::CreateMaybeMessage<::Acoustid::Server::PB::DeleteIndexRequest>(Arena*);
template<> ::Acoustid::Server::PB::DeleteIndexResponse* Arena::CreateMaybeMessage<::Acoustid::Server::PB::DeleteIndexResponse>(Arena*);
template<> ::Acoustid::Server::PB::GetDocumentRequest* Arena::CreateMaybeMessage<::Acoustid::Server::PB::GetDocumentRequest>(Arena*);
template<> ::Acoustid::Server::PB::GetDocumentResponse* Arena::CreateMaybeMessage<::Acoustid::Server::PB::GetDocumentResponse>(Arena*);
template<> ::Acoustid::Server::PB::GetIndexRequest* Arena::CreateMaybeMessage<::Acoustid::Server::PB::GetIndexRequest>(Arena*);
template<> ::Acoustid::Server::PB::GetIndexResponse* Arena::CreateMaybeMessage<::Acoustid::Server::PB::GetIndexResponse>(Arena*);
template<> ::Acoustid::Server::PB::InsertOrUpdateDocumentRequest* Arena::CreateMaybeMessage<::Acoustid::Server::PB::InsertOrUpdateDocumentRequest>(Arena*);
template<> ::Acoustid::Server::PB::InsertOrUpdateDocumentResponse* Arena::CreateMaybeMessage<::Acoustid::Server::PB::InsertOrUpdateDocumentResponse>(Arena*);
template<> ::Acoustid::Server::PB::SearchRequest* Arena::CreateMaybeMessage<::Acoustid::Server::PB::SearchRequest>(Arena*);
template<> ::Acoustid::Server::PB::SearchResponse* Arena::CreateMaybeMessage<::Acoustid::Server::PB::SearchResponse>(Arena*);
template<> ::Acoustid::Server::PB::SearchResult* Arena::CreateMaybeMessage<::Acoustid::Server::PB::SearchResult>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Acoustid {
namespace Server {
namespace PB {

// ===================================================================

class GetIndexRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Acoustid.Server.PB.GetIndexRequest) */ {
 public:
  GetIndexRequest();
  virtual ~GetIndexRequest();

  GetIndexRequest(const GetIndexRequest& from);

  inline GetIndexRequest& operator=(const GetIndexRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetIndexRequest(GetIndexRequest&& from) noexcept
    : GetIndexRequest() {
    *this = ::std::move(from);
  }

  inline GetIndexRequest& operator=(GetIndexRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetIndexRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetIndexRequest* internal_default_instance() {
    return reinterpret_cast<const GetIndexRequest*>(
               &_GetIndexRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(GetIndexRequest* other);
  friend void swap(GetIndexRequest& a, GetIndexRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetIndexRequest* New() const final {
    return CreateMaybeMessage<GetIndexRequest>(NULL);
  }

  GetIndexRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetIndexRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetIndexRequest& from);
  void MergeFrom(const GetIndexRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetIndexRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string index_name = 1;
  void clear_index_name();
  static const int kIndexNameFieldNumber = 1;
  const ::std::string& index_name() const;
  void set_index_name(const ::std::string& value);
  #if LANG_CXX11
  void set_index_name(::std::string&& value);
  #endif
  void set_index_name(const char* value);
  void set_index_name(const char* value, size_t size);
  ::std::string* mutable_index_name();
  ::std::string* release_index_name();
  void set_allocated_index_name(::std::string* index_name);

  // @@protoc_insertion_point(class_scope:Acoustid.Server.PB.GetIndexRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr index_name_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_index_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetIndexResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Acoustid.Server.PB.GetIndexResponse) */ {
 public:
  GetIndexResponse();
  virtual ~GetIndexResponse();

  GetIndexResponse(const GetIndexResponse& from);

  inline GetIndexResponse& operator=(const GetIndexResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetIndexResponse(GetIndexResponse&& from) noexcept
    : GetIndexResponse() {
    *this = ::std::move(from);
  }

  inline GetIndexResponse& operator=(GetIndexResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetIndexResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetIndexResponse* internal_default_instance() {
    return reinterpret_cast<const GetIndexResponse*>(
               &_GetIndexResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(GetIndexResponse* other);
  friend void swap(GetIndexResponse& a, GetIndexResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetIndexResponse* New() const final {
    return CreateMaybeMessage<GetIndexResponse>(NULL);
  }

  GetIndexResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetIndexResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetIndexResponse& from);
  void MergeFrom(const GetIndexResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetIndexResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Acoustid.Server.PB.GetIndexResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_index_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CreateIndexRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Acoustid.Server.PB.CreateIndexRequest) */ {
 public:
  CreateIndexRequest();
  virtual ~CreateIndexRequest();

  CreateIndexRequest(const CreateIndexRequest& from);

  inline CreateIndexRequest& operator=(const CreateIndexRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CreateIndexRequest(CreateIndexRequest&& from) noexcept
    : CreateIndexRequest() {
    *this = ::std::move(from);
  }

  inline CreateIndexRequest& operator=(CreateIndexRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateIndexRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CreateIndexRequest* internal_default_instance() {
    return reinterpret_cast<const CreateIndexRequest*>(
               &_CreateIndexRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(CreateIndexRequest* other);
  friend void swap(CreateIndexRequest& a, CreateIndexRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CreateIndexRequest* New() const final {
    return CreateMaybeMessage<CreateIndexRequest>(NULL);
  }

  CreateIndexRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CreateIndexRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CreateIndexRequest& from);
  void MergeFrom(const CreateIndexRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateIndexRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string index_name = 1;
  void clear_index_name();
  static const int kIndexNameFieldNumber = 1;
  const ::std::string& index_name() const;
  void set_index_name(const ::std::string& value);
  #if LANG_CXX11
  void set_index_name(::std::string&& value);
  #endif
  void set_index_name(const char* value);
  void set_index_name(const char* value, size_t size);
  ::std::string* mutable_index_name();
  ::std::string* release_index_name();
  void set_allocated_index_name(::std::string* index_name);

  // @@protoc_insertion_point(class_scope:Acoustid.Server.PB.CreateIndexRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr index_name_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_index_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CreateIndexResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Acoustid.Server.PB.CreateIndexResponse) */ {
 public:
  CreateIndexResponse();
  virtual ~CreateIndexResponse();

  CreateIndexResponse(const CreateIndexResponse& from);

  inline CreateIndexResponse& operator=(const CreateIndexResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CreateIndexResponse(CreateIndexResponse&& from) noexcept
    : CreateIndexResponse() {
    *this = ::std::move(from);
  }

  inline CreateIndexResponse& operator=(CreateIndexResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateIndexResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CreateIndexResponse* internal_default_instance() {
    return reinterpret_cast<const CreateIndexResponse*>(
               &_CreateIndexResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(CreateIndexResponse* other);
  friend void swap(CreateIndexResponse& a, CreateIndexResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CreateIndexResponse* New() const final {
    return CreateMaybeMessage<CreateIndexResponse>(NULL);
  }

  CreateIndexResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CreateIndexResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CreateIndexResponse& from);
  void MergeFrom(const CreateIndexResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateIndexResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Acoustid.Server.PB.CreateIndexResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_index_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeleteIndexRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Acoustid.Server.PB.DeleteIndexRequest) */ {
 public:
  DeleteIndexRequest();
  virtual ~DeleteIndexRequest();

  DeleteIndexRequest(const DeleteIndexRequest& from);

  inline DeleteIndexRequest& operator=(const DeleteIndexRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeleteIndexRequest(DeleteIndexRequest&& from) noexcept
    : DeleteIndexRequest() {
    *this = ::std::move(from);
  }

  inline DeleteIndexRequest& operator=(DeleteIndexRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteIndexRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeleteIndexRequest* internal_default_instance() {
    return reinterpret_cast<const DeleteIndexRequest*>(
               &_DeleteIndexRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(DeleteIndexRequest* other);
  friend void swap(DeleteIndexRequest& a, DeleteIndexRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeleteIndexRequest* New() const final {
    return CreateMaybeMessage<DeleteIndexRequest>(NULL);
  }

  DeleteIndexRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeleteIndexRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeleteIndexRequest& from);
  void MergeFrom(const DeleteIndexRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeleteIndexRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string index_name = 1;
  void clear_index_name();
  static const int kIndexNameFieldNumber = 1;
  const ::std::string& index_name() const;
  void set_index_name(const ::std::string& value);
  #if LANG_CXX11
  void set_index_name(::std::string&& value);
  #endif
  void set_index_name(const char* value);
  void set_index_name(const char* value, size_t size);
  ::std::string* mutable_index_name();
  ::std::string* release_index_name();
  void set_allocated_index_name(::std::string* index_name);

  // @@protoc_insertion_point(class_scope:Acoustid.Server.PB.DeleteIndexRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr index_name_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_index_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeleteIndexResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Acoustid.Server.PB.DeleteIndexResponse) */ {
 public:
  DeleteIndexResponse();
  virtual ~DeleteIndexResponse();

  DeleteIndexResponse(const DeleteIndexResponse& from);

  inline DeleteIndexResponse& operator=(const DeleteIndexResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeleteIndexResponse(DeleteIndexResponse&& from) noexcept
    : DeleteIndexResponse() {
    *this = ::std::move(from);
  }

  inline DeleteIndexResponse& operator=(DeleteIndexResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteIndexResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeleteIndexResponse* internal_default_instance() {
    return reinterpret_cast<const DeleteIndexResponse*>(
               &_DeleteIndexResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(DeleteIndexResponse* other);
  friend void swap(DeleteIndexResponse& a, DeleteIndexResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeleteIndexResponse* New() const final {
    return CreateMaybeMessage<DeleteIndexResponse>(NULL);
  }

  DeleteIndexResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeleteIndexResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeleteIndexResponse& from);
  void MergeFrom(const DeleteIndexResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeleteIndexResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Acoustid.Server.PB.DeleteIndexResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_index_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetDocumentRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Acoustid.Server.PB.GetDocumentRequest) */ {
 public:
  GetDocumentRequest();
  virtual ~GetDocumentRequest();

  GetDocumentRequest(const GetDocumentRequest& from);

  inline GetDocumentRequest& operator=(const GetDocumentRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetDocumentRequest(GetDocumentRequest&& from) noexcept
    : GetDocumentRequest() {
    *this = ::std::move(from);
  }

  inline GetDocumentRequest& operator=(GetDocumentRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetDocumentRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetDocumentRequest* internal_default_instance() {
    return reinterpret_cast<const GetDocumentRequest*>(
               &_GetDocumentRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(GetDocumentRequest* other);
  friend void swap(GetDocumentRequest& a, GetDocumentRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetDocumentRequest* New() const final {
    return CreateMaybeMessage<GetDocumentRequest>(NULL);
  }

  GetDocumentRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetDocumentRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetDocumentRequest& from);
  void MergeFrom(const GetDocumentRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetDocumentRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string index_name = 1;
  void clear_index_name();
  static const int kIndexNameFieldNumber = 1;
  const ::std::string& index_name() const;
  void set_index_name(const ::std::string& value);
  #if LANG_CXX11
  void set_index_name(::std::string&& value);
  #endif
  void set_index_name(const char* value);
  void set_index_name(const char* value, size_t size);
  ::std::string* mutable_index_name();
  ::std::string* release_index_name();
  void set_allocated_index_name(::std::string* index_name);

  // uint32 doc_id = 2;
  void clear_doc_id();
  static const int kDocIdFieldNumber = 2;
  ::google::protobuf::uint32 doc_id() const;
  void set_doc_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Acoustid.Server.PB.GetDocumentRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr index_name_;
  ::google::protobuf::uint32 doc_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_index_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetDocumentResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Acoustid.Server.PB.GetDocumentResponse) */ {
 public:
  GetDocumentResponse();
  virtual ~GetDocumentResponse();

  GetDocumentResponse(const GetDocumentResponse& from);

  inline GetDocumentResponse& operator=(const GetDocumentResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetDocumentResponse(GetDocumentResponse&& from) noexcept
    : GetDocumentResponse() {
    *this = ::std::move(from);
  }

  inline GetDocumentResponse& operator=(GetDocumentResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetDocumentResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetDocumentResponse* internal_default_instance() {
    return reinterpret_cast<const GetDocumentResponse*>(
               &_GetDocumentResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(GetDocumentResponse* other);
  friend void swap(GetDocumentResponse& a, GetDocumentResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetDocumentResponse* New() const final {
    return CreateMaybeMessage<GetDocumentResponse>(NULL);
  }

  GetDocumentResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetDocumentResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetDocumentResponse& from);
  void MergeFrom(const GetDocumentResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetDocumentResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 terms = 1;
  int terms_size() const;
  void clear_terms();
  static const int kTermsFieldNumber = 1;
  ::google::protobuf::uint32 terms(int index) const;
  void set_terms(int index, ::google::protobuf::uint32 value);
  void add_terms(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      terms() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_terms();

  // @@protoc_insertion_point(class_scope:Acoustid.Server.PB.GetDocumentResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > terms_;
  mutable int _terms_cached_byte_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_index_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class InsertOrUpdateDocumentRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Acoustid.Server.PB.InsertOrUpdateDocumentRequest) */ {
 public:
  InsertOrUpdateDocumentRequest();
  virtual ~InsertOrUpdateDocumentRequest();

  InsertOrUpdateDocumentRequest(const InsertOrUpdateDocumentRequest& from);

  inline InsertOrUpdateDocumentRequest& operator=(const InsertOrUpdateDocumentRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InsertOrUpdateDocumentRequest(InsertOrUpdateDocumentRequest&& from) noexcept
    : InsertOrUpdateDocumentRequest() {
    *this = ::std::move(from);
  }

  inline InsertOrUpdateDocumentRequest& operator=(InsertOrUpdateDocumentRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const InsertOrUpdateDocumentRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InsertOrUpdateDocumentRequest* internal_default_instance() {
    return reinterpret_cast<const InsertOrUpdateDocumentRequest*>(
               &_InsertOrUpdateDocumentRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(InsertOrUpdateDocumentRequest* other);
  friend void swap(InsertOrUpdateDocumentRequest& a, InsertOrUpdateDocumentRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InsertOrUpdateDocumentRequest* New() const final {
    return CreateMaybeMessage<InsertOrUpdateDocumentRequest>(NULL);
  }

  InsertOrUpdateDocumentRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InsertOrUpdateDocumentRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InsertOrUpdateDocumentRequest& from);
  void MergeFrom(const InsertOrUpdateDocumentRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InsertOrUpdateDocumentRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 terms = 3;
  int terms_size() const;
  void clear_terms();
  static const int kTermsFieldNumber = 3;
  ::google::protobuf::uint32 terms(int index) const;
  void set_terms(int index, ::google::protobuf::uint32 value);
  void add_terms(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      terms() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_terms();

  // string index_name = 1;
  void clear_index_name();
  static const int kIndexNameFieldNumber = 1;
  const ::std::string& index_name() const;
  void set_index_name(const ::std::string& value);
  #if LANG_CXX11
  void set_index_name(::std::string&& value);
  #endif
  void set_index_name(const char* value);
  void set_index_name(const char* value, size_t size);
  ::std::string* mutable_index_name();
  ::std::string* release_index_name();
  void set_allocated_index_name(::std::string* index_name);

  // uint32 doc_id = 2;
  void clear_doc_id();
  static const int kDocIdFieldNumber = 2;
  ::google::protobuf::uint32 doc_id() const;
  void set_doc_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Acoustid.Server.PB.InsertOrUpdateDocumentRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > terms_;
  mutable int _terms_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr index_name_;
  ::google::protobuf::uint32 doc_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_index_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class InsertOrUpdateDocumentResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Acoustid.Server.PB.InsertOrUpdateDocumentResponse) */ {
 public:
  InsertOrUpdateDocumentResponse();
  virtual ~InsertOrUpdateDocumentResponse();

  InsertOrUpdateDocumentResponse(const InsertOrUpdateDocumentResponse& from);

  inline InsertOrUpdateDocumentResponse& operator=(const InsertOrUpdateDocumentResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InsertOrUpdateDocumentResponse(InsertOrUpdateDocumentResponse&& from) noexcept
    : InsertOrUpdateDocumentResponse() {
    *this = ::std::move(from);
  }

  inline InsertOrUpdateDocumentResponse& operator=(InsertOrUpdateDocumentResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const InsertOrUpdateDocumentResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InsertOrUpdateDocumentResponse* internal_default_instance() {
    return reinterpret_cast<const InsertOrUpdateDocumentResponse*>(
               &_InsertOrUpdateDocumentResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  void Swap(InsertOrUpdateDocumentResponse* other);
  friend void swap(InsertOrUpdateDocumentResponse& a, InsertOrUpdateDocumentResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InsertOrUpdateDocumentResponse* New() const final {
    return CreateMaybeMessage<InsertOrUpdateDocumentResponse>(NULL);
  }

  InsertOrUpdateDocumentResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InsertOrUpdateDocumentResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InsertOrUpdateDocumentResponse& from);
  void MergeFrom(const InsertOrUpdateDocumentResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InsertOrUpdateDocumentResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Acoustid.Server.PB.InsertOrUpdateDocumentResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_index_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeleteDocumentRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Acoustid.Server.PB.DeleteDocumentRequest) */ {
 public:
  DeleteDocumentRequest();
  virtual ~DeleteDocumentRequest();

  DeleteDocumentRequest(const DeleteDocumentRequest& from);

  inline DeleteDocumentRequest& operator=(const DeleteDocumentRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeleteDocumentRequest(DeleteDocumentRequest&& from) noexcept
    : DeleteDocumentRequest() {
    *this = ::std::move(from);
  }

  inline DeleteDocumentRequest& operator=(DeleteDocumentRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteDocumentRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeleteDocumentRequest* internal_default_instance() {
    return reinterpret_cast<const DeleteDocumentRequest*>(
               &_DeleteDocumentRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  void Swap(DeleteDocumentRequest* other);
  friend void swap(DeleteDocumentRequest& a, DeleteDocumentRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeleteDocumentRequest* New() const final {
    return CreateMaybeMessage<DeleteDocumentRequest>(NULL);
  }

  DeleteDocumentRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeleteDocumentRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeleteDocumentRequest& from);
  void MergeFrom(const DeleteDocumentRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeleteDocumentRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string index_name = 1;
  void clear_index_name();
  static const int kIndexNameFieldNumber = 1;
  const ::std::string& index_name() const;
  void set_index_name(const ::std::string& value);
  #if LANG_CXX11
  void set_index_name(::std::string&& value);
  #endif
  void set_index_name(const char* value);
  void set_index_name(const char* value, size_t size);
  ::std::string* mutable_index_name();
  ::std::string* release_index_name();
  void set_allocated_index_name(::std::string* index_name);

  // uint32 doc_id = 2;
  void clear_doc_id();
  static const int kDocIdFieldNumber = 2;
  ::google::protobuf::uint32 doc_id() const;
  void set_doc_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Acoustid.Server.PB.DeleteDocumentRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr index_name_;
  ::google::protobuf::uint32 doc_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_index_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeleteDocumentResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Acoustid.Server.PB.DeleteDocumentResponse) */ {
 public:
  DeleteDocumentResponse();
  virtual ~DeleteDocumentResponse();

  DeleteDocumentResponse(const DeleteDocumentResponse& from);

  inline DeleteDocumentResponse& operator=(const DeleteDocumentResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeleteDocumentResponse(DeleteDocumentResponse&& from) noexcept
    : DeleteDocumentResponse() {
    *this = ::std::move(from);
  }

  inline DeleteDocumentResponse& operator=(DeleteDocumentResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteDocumentResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeleteDocumentResponse* internal_default_instance() {
    return reinterpret_cast<const DeleteDocumentResponse*>(
               &_DeleteDocumentResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    11;

  void Swap(DeleteDocumentResponse* other);
  friend void swap(DeleteDocumentResponse& a, DeleteDocumentResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeleteDocumentResponse* New() const final {
    return CreateMaybeMessage<DeleteDocumentResponse>(NULL);
  }

  DeleteDocumentResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeleteDocumentResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeleteDocumentResponse& from);
  void MergeFrom(const DeleteDocumentResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeleteDocumentResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Acoustid.Server.PB.DeleteDocumentResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_index_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SearchRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Acoustid.Server.PB.SearchRequest) */ {
 public:
  SearchRequest();
  virtual ~SearchRequest();

  SearchRequest(const SearchRequest& from);

  inline SearchRequest& operator=(const SearchRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SearchRequest(SearchRequest&& from) noexcept
    : SearchRequest() {
    *this = ::std::move(from);
  }

  inline SearchRequest& operator=(SearchRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SearchRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SearchRequest* internal_default_instance() {
    return reinterpret_cast<const SearchRequest*>(
               &_SearchRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    12;

  void Swap(SearchRequest* other);
  friend void swap(SearchRequest& a, SearchRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SearchRequest* New() const final {
    return CreateMaybeMessage<SearchRequest>(NULL);
  }

  SearchRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SearchRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SearchRequest& from);
  void MergeFrom(const SearchRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SearchRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 terms = 2;
  int terms_size() const;
  void clear_terms();
  static const int kTermsFieldNumber = 2;
  ::google::protobuf::uint32 terms(int index) const;
  void set_terms(int index, ::google::protobuf::uint32 value);
  void add_terms(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      terms() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_terms();

  // string index_name = 1;
  void clear_index_name();
  static const int kIndexNameFieldNumber = 1;
  const ::std::string& index_name() const;
  void set_index_name(const ::std::string& value);
  #if LANG_CXX11
  void set_index_name(::std::string&& value);
  #endif
  void set_index_name(const char* value);
  void set_index_name(const char* value, size_t size);
  ::std::string* mutable_index_name();
  ::std::string* release_index_name();
  void set_allocated_index_name(::std::string* index_name);

  // int32 max_results = 3;
  void clear_max_results();
  static const int kMaxResultsFieldNumber = 3;
  ::google::protobuf::int32 max_results() const;
  void set_max_results(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Acoustid.Server.PB.SearchRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > terms_;
  mutable int _terms_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr index_name_;
  ::google::protobuf::int32 max_results_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_index_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SearchResult : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Acoustid.Server.PB.SearchResult) */ {
 public:
  SearchResult();
  virtual ~SearchResult();

  SearchResult(const SearchResult& from);

  inline SearchResult& operator=(const SearchResult& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SearchResult(SearchResult&& from) noexcept
    : SearchResult() {
    *this = ::std::move(from);
  }

  inline SearchResult& operator=(SearchResult&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SearchResult& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SearchResult* internal_default_instance() {
    return reinterpret_cast<const SearchResult*>(
               &_SearchResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    13;

  void Swap(SearchResult* other);
  friend void swap(SearchResult& a, SearchResult& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SearchResult* New() const final {
    return CreateMaybeMessage<SearchResult>(NULL);
  }

  SearchResult* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SearchResult>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SearchResult& from);
  void MergeFrom(const SearchResult& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SearchResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 doc_id = 1;
  void clear_doc_id();
  static const int kDocIdFieldNumber = 1;
  ::google::protobuf::uint32 doc_id() const;
  void set_doc_id(::google::protobuf::uint32 value);

  // float score = 2;
  void clear_score();
  static const int kScoreFieldNumber = 2;
  float score() const;
  void set_score(float value);

  // @@protoc_insertion_point(class_scope:Acoustid.Server.PB.SearchResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 doc_id_;
  float score_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_index_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SearchResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Acoustid.Server.PB.SearchResponse) */ {
 public:
  SearchResponse();
  virtual ~SearchResponse();

  SearchResponse(const SearchResponse& from);

  inline SearchResponse& operator=(const SearchResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SearchResponse(SearchResponse&& from) noexcept
    : SearchResponse() {
    *this = ::std::move(from);
  }

  inline SearchResponse& operator=(SearchResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SearchResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SearchResponse* internal_default_instance() {
    return reinterpret_cast<const SearchResponse*>(
               &_SearchResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    14;

  void Swap(SearchResponse* other);
  friend void swap(SearchResponse& a, SearchResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SearchResponse* New() const final {
    return CreateMaybeMessage<SearchResponse>(NULL);
  }

  SearchResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SearchResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SearchResponse& from);
  void MergeFrom(const SearchResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SearchResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Acoustid.Server.PB.SearchResult results = 1;
  int results_size() const;
  void clear_results();
  static const int kResultsFieldNumber = 1;
  ::Acoustid::Server::PB::SearchResult* mutable_results(int index);
  ::google::protobuf::RepeatedPtrField< ::Acoustid::Server::PB::SearchResult >*
      mutable_results();
  const ::Acoustid::Server::PB::SearchResult& results(int index) const;
  ::Acoustid::Server::PB::SearchResult* add_results();
  const ::google::protobuf::RepeatedPtrField< ::Acoustid::Server::PB::SearchResult >&
      results() const;

  // @@protoc_insertion_point(class_scope:Acoustid.Server.PB.SearchResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Acoustid::Server::PB::SearchResult > results_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_index_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetIndexRequest

// string index_name = 1;
inline void GetIndexRequest::clear_index_name() {
  index_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetIndexRequest::index_name() const {
  // @@protoc_insertion_point(field_get:Acoustid.Server.PB.GetIndexRequest.index_name)
  return index_name_.GetNoArena();
}
inline void GetIndexRequest::set_index_name(const ::std::string& value) {
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Acoustid.Server.PB.GetIndexRequest.index_name)
}
#if LANG_CXX11
inline void GetIndexRequest::set_index_name(::std::string&& value) {
  
  index_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Acoustid.Server.PB.GetIndexRequest.index_name)
}
#endif
inline void GetIndexRequest::set_index_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Acoustid.Server.PB.GetIndexRequest.index_name)
}
inline void GetIndexRequest::set_index_name(const char* value, size_t size) {
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Acoustid.Server.PB.GetIndexRequest.index_name)
}
inline ::std::string* GetIndexRequest::mutable_index_name() {
  
  // @@protoc_insertion_point(field_mutable:Acoustid.Server.PB.GetIndexRequest.index_name)
  return index_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetIndexRequest::release_index_name() {
  // @@protoc_insertion_point(field_release:Acoustid.Server.PB.GetIndexRequest.index_name)
  
  return index_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetIndexRequest::set_allocated_index_name(::std::string* index_name) {
  if (index_name != NULL) {
    
  } else {
    
  }
  index_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), index_name);
  // @@protoc_insertion_point(field_set_allocated:Acoustid.Server.PB.GetIndexRequest.index_name)
}

// -------------------------------------------------------------------

// GetIndexResponse

// -------------------------------------------------------------------

// CreateIndexRequest

// string index_name = 1;
inline void CreateIndexRequest::clear_index_name() {
  index_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CreateIndexRequest::index_name() const {
  // @@protoc_insertion_point(field_get:Acoustid.Server.PB.CreateIndexRequest.index_name)
  return index_name_.GetNoArena();
}
inline void CreateIndexRequest::set_index_name(const ::std::string& value) {
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Acoustid.Server.PB.CreateIndexRequest.index_name)
}
#if LANG_CXX11
inline void CreateIndexRequest::set_index_name(::std::string&& value) {
  
  index_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Acoustid.Server.PB.CreateIndexRequest.index_name)
}
#endif
inline void CreateIndexRequest::set_index_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Acoustid.Server.PB.CreateIndexRequest.index_name)
}
inline void CreateIndexRequest::set_index_name(const char* value, size_t size) {
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Acoustid.Server.PB.CreateIndexRequest.index_name)
}
inline ::std::string* CreateIndexRequest::mutable_index_name() {
  
  // @@protoc_insertion_point(field_mutable:Acoustid.Server.PB.CreateIndexRequest.index_name)
  return index_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CreateIndexRequest::release_index_name() {
  // @@protoc_insertion_point(field_release:Acoustid.Server.PB.CreateIndexRequest.index_name)
  
  return index_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateIndexRequest::set_allocated_index_name(::std::string* index_name) {
  if (index_name != NULL) {
    
  } else {
    
  }
  index_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), index_name);
  // @@protoc_insertion_point(field_set_allocated:Acoustid.Server.PB.CreateIndexRequest.index_name)
}

// -------------------------------------------------------------------

// CreateIndexResponse

// -------------------------------------------------------------------

// DeleteIndexRequest

// string index_name = 1;
inline void DeleteIndexRequest::clear_index_name() {
  index_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeleteIndexRequest::index_name() const {
  // @@protoc_insertion_point(field_get:Acoustid.Server.PB.DeleteIndexRequest.index_name)
  return index_name_.GetNoArena();
}
inline void DeleteIndexRequest::set_index_name(const ::std::string& value) {
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Acoustid.Server.PB.DeleteIndexRequest.index_name)
}
#if LANG_CXX11
inline void DeleteIndexRequest::set_index_name(::std::string&& value) {
  
  index_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Acoustid.Server.PB.DeleteIndexRequest.index_name)
}
#endif
inline void DeleteIndexRequest::set_index_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Acoustid.Server.PB.DeleteIndexRequest.index_name)
}
inline void DeleteIndexRequest::set_index_name(const char* value, size_t size) {
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Acoustid.Server.PB.DeleteIndexRequest.index_name)
}
inline ::std::string* DeleteIndexRequest::mutable_index_name() {
  
  // @@protoc_insertion_point(field_mutable:Acoustid.Server.PB.DeleteIndexRequest.index_name)
  return index_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeleteIndexRequest::release_index_name() {
  // @@protoc_insertion_point(field_release:Acoustid.Server.PB.DeleteIndexRequest.index_name)
  
  return index_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeleteIndexRequest::set_allocated_index_name(::std::string* index_name) {
  if (index_name != NULL) {
    
  } else {
    
  }
  index_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), index_name);
  // @@protoc_insertion_point(field_set_allocated:Acoustid.Server.PB.DeleteIndexRequest.index_name)
}

// -------------------------------------------------------------------

// DeleteIndexResponse

// -------------------------------------------------------------------

// GetDocumentRequest

// string index_name = 1;
inline void GetDocumentRequest::clear_index_name() {
  index_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetDocumentRequest::index_name() const {
  // @@protoc_insertion_point(field_get:Acoustid.Server.PB.GetDocumentRequest.index_name)
  return index_name_.GetNoArena();
}
inline void GetDocumentRequest::set_index_name(const ::std::string& value) {
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Acoustid.Server.PB.GetDocumentRequest.index_name)
}
#if LANG_CXX11
inline void GetDocumentRequest::set_index_name(::std::string&& value) {
  
  index_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Acoustid.Server.PB.GetDocumentRequest.index_name)
}
#endif
inline void GetDocumentRequest::set_index_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Acoustid.Server.PB.GetDocumentRequest.index_name)
}
inline void GetDocumentRequest::set_index_name(const char* value, size_t size) {
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Acoustid.Server.PB.GetDocumentRequest.index_name)
}
inline ::std::string* GetDocumentRequest::mutable_index_name() {
  
  // @@protoc_insertion_point(field_mutable:Acoustid.Server.PB.GetDocumentRequest.index_name)
  return index_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetDocumentRequest::release_index_name() {
  // @@protoc_insertion_point(field_release:Acoustid.Server.PB.GetDocumentRequest.index_name)
  
  return index_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetDocumentRequest::set_allocated_index_name(::std::string* index_name) {
  if (index_name != NULL) {
    
  } else {
    
  }
  index_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), index_name);
  // @@protoc_insertion_point(field_set_allocated:Acoustid.Server.PB.GetDocumentRequest.index_name)
}

// uint32 doc_id = 2;
inline void GetDocumentRequest::clear_doc_id() {
  doc_id_ = 0u;
}
inline ::google::protobuf::uint32 GetDocumentRequest::doc_id() const {
  // @@protoc_insertion_point(field_get:Acoustid.Server.PB.GetDocumentRequest.doc_id)
  return doc_id_;
}
inline void GetDocumentRequest::set_doc_id(::google::protobuf::uint32 value) {
  
  doc_id_ = value;
  // @@protoc_insertion_point(field_set:Acoustid.Server.PB.GetDocumentRequest.doc_id)
}

// -------------------------------------------------------------------

// GetDocumentResponse

// repeated uint32 terms = 1;
inline int GetDocumentResponse::terms_size() const {
  return terms_.size();
}
inline void GetDocumentResponse::clear_terms() {
  terms_.Clear();
}
inline ::google::protobuf::uint32 GetDocumentResponse::terms(int index) const {
  // @@protoc_insertion_point(field_get:Acoustid.Server.PB.GetDocumentResponse.terms)
  return terms_.Get(index);
}
inline void GetDocumentResponse::set_terms(int index, ::google::protobuf::uint32 value) {
  terms_.Set(index, value);
  // @@protoc_insertion_point(field_set:Acoustid.Server.PB.GetDocumentResponse.terms)
}
inline void GetDocumentResponse::add_terms(::google::protobuf::uint32 value) {
  terms_.Add(value);
  // @@protoc_insertion_point(field_add:Acoustid.Server.PB.GetDocumentResponse.terms)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
GetDocumentResponse::terms() const {
  // @@protoc_insertion_point(field_list:Acoustid.Server.PB.GetDocumentResponse.terms)
  return terms_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
GetDocumentResponse::mutable_terms() {
  // @@protoc_insertion_point(field_mutable_list:Acoustid.Server.PB.GetDocumentResponse.terms)
  return &terms_;
}

// -------------------------------------------------------------------

// InsertOrUpdateDocumentRequest

// string index_name = 1;
inline void InsertOrUpdateDocumentRequest::clear_index_name() {
  index_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& InsertOrUpdateDocumentRequest::index_name() const {
  // @@protoc_insertion_point(field_get:Acoustid.Server.PB.InsertOrUpdateDocumentRequest.index_name)
  return index_name_.GetNoArena();
}
inline void InsertOrUpdateDocumentRequest::set_index_name(const ::std::string& value) {
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Acoustid.Server.PB.InsertOrUpdateDocumentRequest.index_name)
}
#if LANG_CXX11
inline void InsertOrUpdateDocumentRequest::set_index_name(::std::string&& value) {
  
  index_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Acoustid.Server.PB.InsertOrUpdateDocumentRequest.index_name)
}
#endif
inline void InsertOrUpdateDocumentRequest::set_index_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Acoustid.Server.PB.InsertOrUpdateDocumentRequest.index_name)
}
inline void InsertOrUpdateDocumentRequest::set_index_name(const char* value, size_t size) {
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Acoustid.Server.PB.InsertOrUpdateDocumentRequest.index_name)
}
inline ::std::string* InsertOrUpdateDocumentRequest::mutable_index_name() {
  
  // @@protoc_insertion_point(field_mutable:Acoustid.Server.PB.InsertOrUpdateDocumentRequest.index_name)
  return index_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* InsertOrUpdateDocumentRequest::release_index_name() {
  // @@protoc_insertion_point(field_release:Acoustid.Server.PB.InsertOrUpdateDocumentRequest.index_name)
  
  return index_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InsertOrUpdateDocumentRequest::set_allocated_index_name(::std::string* index_name) {
  if (index_name != NULL) {
    
  } else {
    
  }
  index_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), index_name);
  // @@protoc_insertion_point(field_set_allocated:Acoustid.Server.PB.InsertOrUpdateDocumentRequest.index_name)
}

// uint32 doc_id = 2;
inline void InsertOrUpdateDocumentRequest::clear_doc_id() {
  doc_id_ = 0u;
}
inline ::google::protobuf::uint32 InsertOrUpdateDocumentRequest::doc_id() const {
  // @@protoc_insertion_point(field_get:Acoustid.Server.PB.InsertOrUpdateDocumentRequest.doc_id)
  return doc_id_;
}
inline void InsertOrUpdateDocumentRequest::set_doc_id(::google::protobuf::uint32 value) {
  
  doc_id_ = value;
  // @@protoc_insertion_point(field_set:Acoustid.Server.PB.InsertOrUpdateDocumentRequest.doc_id)
}

// repeated uint32 terms = 3;
inline int InsertOrUpdateDocumentRequest::terms_size() const {
  return terms_.size();
}
inline void InsertOrUpdateDocumentRequest::clear_terms() {
  terms_.Clear();
}
inline ::google::protobuf::uint32 InsertOrUpdateDocumentRequest::terms(int index) const {
  // @@protoc_insertion_point(field_get:Acoustid.Server.PB.InsertOrUpdateDocumentRequest.terms)
  return terms_.Get(index);
}
inline void InsertOrUpdateDocumentRequest::set_terms(int index, ::google::protobuf::uint32 value) {
  terms_.Set(index, value);
  // @@protoc_insertion_point(field_set:Acoustid.Server.PB.InsertOrUpdateDocumentRequest.terms)
}
inline void InsertOrUpdateDocumentRequest::add_terms(::google::protobuf::uint32 value) {
  terms_.Add(value);
  // @@protoc_insertion_point(field_add:Acoustid.Server.PB.InsertOrUpdateDocumentRequest.terms)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
InsertOrUpdateDocumentRequest::terms() const {
  // @@protoc_insertion_point(field_list:Acoustid.Server.PB.InsertOrUpdateDocumentRequest.terms)
  return terms_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
InsertOrUpdateDocumentRequest::mutable_terms() {
  // @@protoc_insertion_point(field_mutable_list:Acoustid.Server.PB.InsertOrUpdateDocumentRequest.terms)
  return &terms_;
}

// -------------------------------------------------------------------

// InsertOrUpdateDocumentResponse

// -------------------------------------------------------------------

// DeleteDocumentRequest

// string index_name = 1;
inline void DeleteDocumentRequest::clear_index_name() {
  index_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeleteDocumentRequest::index_name() const {
  // @@protoc_insertion_point(field_get:Acoustid.Server.PB.DeleteDocumentRequest.index_name)
  return index_name_.GetNoArena();
}
inline void DeleteDocumentRequest::set_index_name(const ::std::string& value) {
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Acoustid.Server.PB.DeleteDocumentRequest.index_name)
}
#if LANG_CXX11
inline void DeleteDocumentRequest::set_index_name(::std::string&& value) {
  
  index_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Acoustid.Server.PB.DeleteDocumentRequest.index_name)
}
#endif
inline void DeleteDocumentRequest::set_index_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Acoustid.Server.PB.DeleteDocumentRequest.index_name)
}
inline void DeleteDocumentRequest::set_index_name(const char* value, size_t size) {
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Acoustid.Server.PB.DeleteDocumentRequest.index_name)
}
inline ::std::string* DeleteDocumentRequest::mutable_index_name() {
  
  // @@protoc_insertion_point(field_mutable:Acoustid.Server.PB.DeleteDocumentRequest.index_name)
  return index_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeleteDocumentRequest::release_index_name() {
  // @@protoc_insertion_point(field_release:Acoustid.Server.PB.DeleteDocumentRequest.index_name)
  
  return index_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeleteDocumentRequest::set_allocated_index_name(::std::string* index_name) {
  if (index_name != NULL) {
    
  } else {
    
  }
  index_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), index_name);
  // @@protoc_insertion_point(field_set_allocated:Acoustid.Server.PB.DeleteDocumentRequest.index_name)
}

// uint32 doc_id = 2;
inline void DeleteDocumentRequest::clear_doc_id() {
  doc_id_ = 0u;
}
inline ::google::protobuf::uint32 DeleteDocumentRequest::doc_id() const {
  // @@protoc_insertion_point(field_get:Acoustid.Server.PB.DeleteDocumentRequest.doc_id)
  return doc_id_;
}
inline void DeleteDocumentRequest::set_doc_id(::google::protobuf::uint32 value) {
  
  doc_id_ = value;
  // @@protoc_insertion_point(field_set:Acoustid.Server.PB.DeleteDocumentRequest.doc_id)
}

// -------------------------------------------------------------------

// DeleteDocumentResponse

// -------------------------------------------------------------------

// SearchRequest

// string index_name = 1;
inline void SearchRequest::clear_index_name() {
  index_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SearchRequest::index_name() const {
  // @@protoc_insertion_point(field_get:Acoustid.Server.PB.SearchRequest.index_name)
  return index_name_.GetNoArena();
}
inline void SearchRequest::set_index_name(const ::std::string& value) {
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Acoustid.Server.PB.SearchRequest.index_name)
}
#if LANG_CXX11
inline void SearchRequest::set_index_name(::std::string&& value) {
  
  index_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Acoustid.Server.PB.SearchRequest.index_name)
}
#endif
inline void SearchRequest::set_index_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Acoustid.Server.PB.SearchRequest.index_name)
}
inline void SearchRequest::set_index_name(const char* value, size_t size) {
  
  index_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Acoustid.Server.PB.SearchRequest.index_name)
}
inline ::std::string* SearchRequest::mutable_index_name() {
  
  // @@protoc_insertion_point(field_mutable:Acoustid.Server.PB.SearchRequest.index_name)
  return index_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SearchRequest::release_index_name() {
  // @@protoc_insertion_point(field_release:Acoustid.Server.PB.SearchRequest.index_name)
  
  return index_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SearchRequest::set_allocated_index_name(::std::string* index_name) {
  if (index_name != NULL) {
    
  } else {
    
  }
  index_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), index_name);
  // @@protoc_insertion_point(field_set_allocated:Acoustid.Server.PB.SearchRequest.index_name)
}

// repeated uint32 terms = 2;
inline int SearchRequest::terms_size() const {
  return terms_.size();
}
inline void SearchRequest::clear_terms() {
  terms_.Clear();
}
inline ::google::protobuf::uint32 SearchRequest::terms(int index) const {
  // @@protoc_insertion_point(field_get:Acoustid.Server.PB.SearchRequest.terms)
  return terms_.Get(index);
}
inline void SearchRequest::set_terms(int index, ::google::protobuf::uint32 value) {
  terms_.Set(index, value);
  // @@protoc_insertion_point(field_set:Acoustid.Server.PB.SearchRequest.terms)
}
inline void SearchRequest::add_terms(::google::protobuf::uint32 value) {
  terms_.Add(value);
  // @@protoc_insertion_point(field_add:Acoustid.Server.PB.SearchRequest.terms)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
SearchRequest::terms() const {
  // @@protoc_insertion_point(field_list:Acoustid.Server.PB.SearchRequest.terms)
  return terms_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
SearchRequest::mutable_terms() {
  // @@protoc_insertion_point(field_mutable_list:Acoustid.Server.PB.SearchRequest.terms)
  return &terms_;
}

// int32 max_results = 3;
inline void SearchRequest::clear_max_results() {
  max_results_ = 0;
}
inline ::google::protobuf::int32 SearchRequest::max_results() const {
  // @@protoc_insertion_point(field_get:Acoustid.Server.PB.SearchRequest.max_results)
  return max_results_;
}
inline void SearchRequest::set_max_results(::google::protobuf::int32 value) {
  
  max_results_ = value;
  // @@protoc_insertion_point(field_set:Acoustid.Server.PB.SearchRequest.max_results)
}

// -------------------------------------------------------------------

// SearchResult

// uint32 doc_id = 1;
inline void SearchResult::clear_doc_id() {
  doc_id_ = 0u;
}
inline ::google::protobuf::uint32 SearchResult::doc_id() const {
  // @@protoc_insertion_point(field_get:Acoustid.Server.PB.SearchResult.doc_id)
  return doc_id_;
}
inline void SearchResult::set_doc_id(::google::protobuf::uint32 value) {
  
  doc_id_ = value;
  // @@protoc_insertion_point(field_set:Acoustid.Server.PB.SearchResult.doc_id)
}

// float score = 2;
inline void SearchResult::clear_score() {
  score_ = 0;
}
inline float SearchResult::score() const {
  // @@protoc_insertion_point(field_get:Acoustid.Server.PB.SearchResult.score)
  return score_;
}
inline void SearchResult::set_score(float value) {
  
  score_ = value;
  // @@protoc_insertion_point(field_set:Acoustid.Server.PB.SearchResult.score)
}

// -------------------------------------------------------------------

// SearchResponse

// repeated .Acoustid.Server.PB.SearchResult results = 1;
inline int SearchResponse::results_size() const {
  return results_.size();
}
inline void SearchResponse::clear_results() {
  results_.Clear();
}
inline ::Acoustid::Server::PB::SearchResult* SearchResponse::mutable_results(int index) {
  // @@protoc_insertion_point(field_mutable:Acoustid.Server.PB.SearchResponse.results)
  return results_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Acoustid::Server::PB::SearchResult >*
SearchResponse::mutable_results() {
  // @@protoc_insertion_point(field_mutable_list:Acoustid.Server.PB.SearchResponse.results)
  return &results_;
}
inline const ::Acoustid::Server::PB::SearchResult& SearchResponse::results(int index) const {
  // @@protoc_insertion_point(field_get:Acoustid.Server.PB.SearchResponse.results)
  return results_.Get(index);
}
inline ::Acoustid::Server::PB::SearchResult* SearchResponse::add_results() {
  // @@protoc_insertion_point(field_add:Acoustid.Server.PB.SearchResponse.results)
  return results_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Acoustid::Server::PB::SearchResult >&
SearchResponse::results() const {
  // @@protoc_insertion_point(field_list:Acoustid.Server.PB.SearchResponse.results)
  return results_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace PB
}  // namespace Server
}  // namespace Acoustid

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_index_2eproto
