// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: index.proto

#include "index.pb.h"
#include "index.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace fpindex {

static const char* Index_method_names[] = {
  "/fpindex.Index/ListIndexes",
  "/fpindex.Index/GetIndex",
  "/fpindex.Index/CreateIndex",
  "/fpindex.Index/DeleteIndex",
  "/fpindex.Index/GetAttribute",
  "/fpindex.Index/Update",
  "/fpindex.Index/Search",
};

std::unique_ptr< Index::Stub> Index::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Index::Stub> stub(new Index::Stub(channel));
  return stub;
}

Index::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_ListIndexes_(Index_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetIndex_(Index_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateIndex_(Index_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteIndex_(Index_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetAttribute_(Index_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Update_(Index_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Search_(Index_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Index::Stub::ListIndexes(::grpc::ClientContext* context, const ::fpindex::ListIndexesRequest& request, ::fpindex::ListIndexesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ListIndexes_, context, request, response);
}

void Index::Stub::experimental_async::ListIndexes(::grpc::ClientContext* context, const ::fpindex::ListIndexesRequest* request, ::fpindex::ListIndexesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ListIndexes_, context, request, response, std::move(f));
}

void Index::Stub::experimental_async::ListIndexes(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fpindex::ListIndexesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ListIndexes_, context, request, response, std::move(f));
}

void Index::Stub::experimental_async::ListIndexes(::grpc::ClientContext* context, const ::fpindex::ListIndexesRequest* request, ::fpindex::ListIndexesResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ListIndexes_, context, request, response, reactor);
}

void Index::Stub::experimental_async::ListIndexes(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fpindex::ListIndexesResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ListIndexes_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fpindex::ListIndexesResponse>* Index::Stub::AsyncListIndexesRaw(::grpc::ClientContext* context, const ::fpindex::ListIndexesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::fpindex::ListIndexesResponse>::Create(channel_.get(), cq, rpcmethod_ListIndexes_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::fpindex::ListIndexesResponse>* Index::Stub::PrepareAsyncListIndexesRaw(::grpc::ClientContext* context, const ::fpindex::ListIndexesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::fpindex::ListIndexesResponse>::Create(channel_.get(), cq, rpcmethod_ListIndexes_, context, request, false);
}

::grpc::Status Index::Stub::GetIndex(::grpc::ClientContext* context, const ::fpindex::GetIndexRequest& request, ::fpindex::GetIndexResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetIndex_, context, request, response);
}

void Index::Stub::experimental_async::GetIndex(::grpc::ClientContext* context, const ::fpindex::GetIndexRequest* request, ::fpindex::GetIndexResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetIndex_, context, request, response, std::move(f));
}

void Index::Stub::experimental_async::GetIndex(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fpindex::GetIndexResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetIndex_, context, request, response, std::move(f));
}

void Index::Stub::experimental_async::GetIndex(::grpc::ClientContext* context, const ::fpindex::GetIndexRequest* request, ::fpindex::GetIndexResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetIndex_, context, request, response, reactor);
}

void Index::Stub::experimental_async::GetIndex(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fpindex::GetIndexResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetIndex_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fpindex::GetIndexResponse>* Index::Stub::AsyncGetIndexRaw(::grpc::ClientContext* context, const ::fpindex::GetIndexRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::fpindex::GetIndexResponse>::Create(channel_.get(), cq, rpcmethod_GetIndex_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::fpindex::GetIndexResponse>* Index::Stub::PrepareAsyncGetIndexRaw(::grpc::ClientContext* context, const ::fpindex::GetIndexRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::fpindex::GetIndexResponse>::Create(channel_.get(), cq, rpcmethod_GetIndex_, context, request, false);
}

::grpc::Status Index::Stub::CreateIndex(::grpc::ClientContext* context, const ::fpindex::CreateIndexRequest& request, ::fpindex::CreateIndexResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreateIndex_, context, request, response);
}

void Index::Stub::experimental_async::CreateIndex(::grpc::ClientContext* context, const ::fpindex::CreateIndexRequest* request, ::fpindex::CreateIndexResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateIndex_, context, request, response, std::move(f));
}

void Index::Stub::experimental_async::CreateIndex(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fpindex::CreateIndexResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateIndex_, context, request, response, std::move(f));
}

void Index::Stub::experimental_async::CreateIndex(::grpc::ClientContext* context, const ::fpindex::CreateIndexRequest* request, ::fpindex::CreateIndexResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateIndex_, context, request, response, reactor);
}

void Index::Stub::experimental_async::CreateIndex(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fpindex::CreateIndexResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateIndex_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fpindex::CreateIndexResponse>* Index::Stub::AsyncCreateIndexRaw(::grpc::ClientContext* context, const ::fpindex::CreateIndexRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::fpindex::CreateIndexResponse>::Create(channel_.get(), cq, rpcmethod_CreateIndex_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::fpindex::CreateIndexResponse>* Index::Stub::PrepareAsyncCreateIndexRaw(::grpc::ClientContext* context, const ::fpindex::CreateIndexRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::fpindex::CreateIndexResponse>::Create(channel_.get(), cq, rpcmethod_CreateIndex_, context, request, false);
}

::grpc::Status Index::Stub::DeleteIndex(::grpc::ClientContext* context, const ::fpindex::DeleteIndexRequest& request, ::fpindex::DeleteIndexResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_DeleteIndex_, context, request, response);
}

void Index::Stub::experimental_async::DeleteIndex(::grpc::ClientContext* context, const ::fpindex::DeleteIndexRequest* request, ::fpindex::DeleteIndexResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DeleteIndex_, context, request, response, std::move(f));
}

void Index::Stub::experimental_async::DeleteIndex(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fpindex::DeleteIndexResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DeleteIndex_, context, request, response, std::move(f));
}

void Index::Stub::experimental_async::DeleteIndex(::grpc::ClientContext* context, const ::fpindex::DeleteIndexRequest* request, ::fpindex::DeleteIndexResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DeleteIndex_, context, request, response, reactor);
}

void Index::Stub::experimental_async::DeleteIndex(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fpindex::DeleteIndexResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DeleteIndex_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fpindex::DeleteIndexResponse>* Index::Stub::AsyncDeleteIndexRaw(::grpc::ClientContext* context, const ::fpindex::DeleteIndexRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::fpindex::DeleteIndexResponse>::Create(channel_.get(), cq, rpcmethod_DeleteIndex_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::fpindex::DeleteIndexResponse>* Index::Stub::PrepareAsyncDeleteIndexRaw(::grpc::ClientContext* context, const ::fpindex::DeleteIndexRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::fpindex::DeleteIndexResponse>::Create(channel_.get(), cq, rpcmethod_DeleteIndex_, context, request, false);
}

::grpc::Status Index::Stub::GetAttribute(::grpc::ClientContext* context, const ::fpindex::GetAttributeRequest& request, ::fpindex::GetAttributeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetAttribute_, context, request, response);
}

void Index::Stub::experimental_async::GetAttribute(::grpc::ClientContext* context, const ::fpindex::GetAttributeRequest* request, ::fpindex::GetAttributeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetAttribute_, context, request, response, std::move(f));
}

void Index::Stub::experimental_async::GetAttribute(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fpindex::GetAttributeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetAttribute_, context, request, response, std::move(f));
}

void Index::Stub::experimental_async::GetAttribute(::grpc::ClientContext* context, const ::fpindex::GetAttributeRequest* request, ::fpindex::GetAttributeResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetAttribute_, context, request, response, reactor);
}

void Index::Stub::experimental_async::GetAttribute(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fpindex::GetAttributeResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetAttribute_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fpindex::GetAttributeResponse>* Index::Stub::AsyncGetAttributeRaw(::grpc::ClientContext* context, const ::fpindex::GetAttributeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::fpindex::GetAttributeResponse>::Create(channel_.get(), cq, rpcmethod_GetAttribute_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::fpindex::GetAttributeResponse>* Index::Stub::PrepareAsyncGetAttributeRaw(::grpc::ClientContext* context, const ::fpindex::GetAttributeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::fpindex::GetAttributeResponse>::Create(channel_.get(), cq, rpcmethod_GetAttribute_, context, request, false);
}

::grpc::Status Index::Stub::Update(::grpc::ClientContext* context, const ::fpindex::UpdateRequest& request, ::fpindex::UpdateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Update_, context, request, response);
}

void Index::Stub::experimental_async::Update(::grpc::ClientContext* context, const ::fpindex::UpdateRequest* request, ::fpindex::UpdateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Update_, context, request, response, std::move(f));
}

void Index::Stub::experimental_async::Update(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fpindex::UpdateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Update_, context, request, response, std::move(f));
}

void Index::Stub::experimental_async::Update(::grpc::ClientContext* context, const ::fpindex::UpdateRequest* request, ::fpindex::UpdateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Update_, context, request, response, reactor);
}

void Index::Stub::experimental_async::Update(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fpindex::UpdateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Update_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fpindex::UpdateResponse>* Index::Stub::AsyncUpdateRaw(::grpc::ClientContext* context, const ::fpindex::UpdateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::fpindex::UpdateResponse>::Create(channel_.get(), cq, rpcmethod_Update_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::fpindex::UpdateResponse>* Index::Stub::PrepareAsyncUpdateRaw(::grpc::ClientContext* context, const ::fpindex::UpdateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::fpindex::UpdateResponse>::Create(channel_.get(), cq, rpcmethod_Update_, context, request, false);
}

::grpc::Status Index::Stub::Search(::grpc::ClientContext* context, const ::fpindex::SearchRequest& request, ::fpindex::SearchResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Search_, context, request, response);
}

void Index::Stub::experimental_async::Search(::grpc::ClientContext* context, const ::fpindex::SearchRequest* request, ::fpindex::SearchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Search_, context, request, response, std::move(f));
}

void Index::Stub::experimental_async::Search(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fpindex::SearchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Search_, context, request, response, std::move(f));
}

void Index::Stub::experimental_async::Search(::grpc::ClientContext* context, const ::fpindex::SearchRequest* request, ::fpindex::SearchResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Search_, context, request, response, reactor);
}

void Index::Stub::experimental_async::Search(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fpindex::SearchResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Search_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fpindex::SearchResponse>* Index::Stub::AsyncSearchRaw(::grpc::ClientContext* context, const ::fpindex::SearchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::fpindex::SearchResponse>::Create(channel_.get(), cq, rpcmethod_Search_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::fpindex::SearchResponse>* Index::Stub::PrepareAsyncSearchRaw(::grpc::ClientContext* context, const ::fpindex::SearchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::fpindex::SearchResponse>::Create(channel_.get(), cq, rpcmethod_Search_, context, request, false);
}

Index::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Index_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Index::Service, ::fpindex::ListIndexesRequest, ::fpindex::ListIndexesResponse>(
          [](Index::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::fpindex::ListIndexesRequest* req,
             ::fpindex::ListIndexesResponse* resp) {
               return service->ListIndexes(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Index_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Index::Service, ::fpindex::GetIndexRequest, ::fpindex::GetIndexResponse>(
          [](Index::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::fpindex::GetIndexRequest* req,
             ::fpindex::GetIndexResponse* resp) {
               return service->GetIndex(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Index_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Index::Service, ::fpindex::CreateIndexRequest, ::fpindex::CreateIndexResponse>(
          [](Index::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::fpindex::CreateIndexRequest* req,
             ::fpindex::CreateIndexResponse* resp) {
               return service->CreateIndex(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Index_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Index::Service, ::fpindex::DeleteIndexRequest, ::fpindex::DeleteIndexResponse>(
          [](Index::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::fpindex::DeleteIndexRequest* req,
             ::fpindex::DeleteIndexResponse* resp) {
               return service->DeleteIndex(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Index_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Index::Service, ::fpindex::GetAttributeRequest, ::fpindex::GetAttributeResponse>(
          [](Index::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::fpindex::GetAttributeRequest* req,
             ::fpindex::GetAttributeResponse* resp) {
               return service->GetAttribute(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Index_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Index::Service, ::fpindex::UpdateRequest, ::fpindex::UpdateResponse>(
          [](Index::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::fpindex::UpdateRequest* req,
             ::fpindex::UpdateResponse* resp) {
               return service->Update(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Index_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Index::Service, ::fpindex::SearchRequest, ::fpindex::SearchResponse>(
          [](Index::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::fpindex::SearchRequest* req,
             ::fpindex::SearchResponse* resp) {
               return service->Search(ctx, req, resp);
             }, this)));
}

Index::Service::~Service() {
}

::grpc::Status Index::Service::ListIndexes(::grpc::ServerContext* context, const ::fpindex::ListIndexesRequest* request, ::fpindex::ListIndexesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Index::Service::GetIndex(::grpc::ServerContext* context, const ::fpindex::GetIndexRequest* request, ::fpindex::GetIndexResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Index::Service::CreateIndex(::grpc::ServerContext* context, const ::fpindex::CreateIndexRequest* request, ::fpindex::CreateIndexResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Index::Service::DeleteIndex(::grpc::ServerContext* context, const ::fpindex::DeleteIndexRequest* request, ::fpindex::DeleteIndexResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Index::Service::GetAttribute(::grpc::ServerContext* context, const ::fpindex::GetAttributeRequest* request, ::fpindex::GetAttributeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Index::Service::Update(::grpc::ServerContext* context, const ::fpindex::UpdateRequest* request, ::fpindex::UpdateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Index::Service::Search(::grpc::ServerContext* context, const ::fpindex::SearchRequest* request, ::fpindex::SearchResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace fpindex

