name: Build fpindex-cluster

on:
  push:
    paths:
      - 'cluster/**'
  pull_request:
    paths:
      - 'cluster/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/fpindex-cluster

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      
      - name: Install dependencies
        run: |
          cd cluster
          uv sync --group dev
      
      - name: Run ruff check
        run: |
          cd cluster
          uv run ruff check .
      
      - name: Run ruff format check
        run: |
          cd cluster
          uv run ruff format --check .

  build:
    runs-on: ubuntu-24.04
    needs: lint
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./cluster
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}